import Vector
from Vector import Vector

# Base World
FRAME_RATE = 60
WORLD_WIDTH = 1024
WORLD_HEIGHT = 768
BACKGROUND_COLOR = (100, 149, 237)
BOUNDARY_RADIUS = 50
BOUNDARY_WEIGHT = 0.2
LEFT_BOUND_NORM = Vector(1,0)
RIGHT_BOUND_NORM = Vector(-1,0)
TOP_BOUND_NORM = Vector(0,1)
BOT_BOUND_NORM = Vector(0,-1)

AGENT_WIDTH = 16
AGENT_HEIGHT = 32

# Player
PLAYER_COLOR = (255, 255, 0)
PLAYER_SIZE = 10
PLAYER_SPEED = 5.5 * 10
DIR_TO_ENEMY_WEIGHT = 1
PLAYER_TURN_SPEED = 0.4

# Constants for colors for debugging
COLOR_BLUE = (0, 0, 255)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)

# Enemies
ENEMY_COLOR = (0, 255, 0)
ENEMY_SIZE = 10
ENEMY_SPEED = 5 * 10
MIN_ATTACK_DIST = 200
WANDER_TURN_RADIUS = 0.1
DIR_FROM_PLAYER_WEIGHT = 0.2
WANDER_WEIGHT = 0.5
ALIGNMENT_WEIGHT = 0.3
COHESION_WEIGHT = 0.3
SEPARATION_WEIGHT = 0.325
NEIGHBOR_MIN_DIST = 50

ENEMY_TURN_SPEED = 0.2

# Debug 
ENABLE_DOG = True
ENABLE_ALIGNMENT = True
ENABLE_COHESION = True
ENABLE_SEPARATION = True
ENABLE_BOUNDARIES = True

DEBUGGING = True
DEBUG_LINE_WIDTH = 1
DEBUG_VELOCITY = DEBUGGING
DEBUG_BOUNDARIES = DEBUGGING
DEBUG_NEIGHBORS = DEBUGGING
DEBUG_DOG_INFLUENCE = DEBUGGING
DEBUG_BOUNDING_RECTS = DEBUGGING